[ req ]
prompt              = no
distinguished_name  = req_dn

[ req_dn ]
C                   = US
ST                  = Minnesota
L                   = Winona
O                   = Konik Systems
OU                  = Firmware Devices
CN                  = firmware-device-001
serialNumber        = ABC-123456