[ req ]
default_bits        = 2048
default_md          = sha256
prompt              = no
encrypt_key         = no
distinguished_name  = req_dn
req_extensions      = req_ext

[ req_dn ]
C                   = US
ST                  = Minnesota
L                   = Winona
O                   = Konik Systems
OU                  = Firmware Devices
CN                  = firmware-device-001
serialNumber        = ABC-123456

[ req_ext ]
basicConstraints    = critical,CA:false
keyUsage            = critical,digitalSignature
extendedKeyUsage    = clientAuth
subjectAltName      = @alt_names

[ alt_names ]
DNS.1               = firmware-device-001.local
URI.1               = urn:device:ABC-123456