[ req ]
prompt              = no
distinguished_name  = req_dn

[ req_dn ]
C                   = US
ST                  = Minnesota
L                   = Winona
O                   = Organization Name
OU                  = Certificate Authority
CN                  = Common Name
serialNumber        = Serial Number